# Generated by Django 2.1 on 2020-11-15 21:01

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_conkurs_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conkurs',
            name='logo',
            field=models.FileField(default='settings.MEDIA_ROOT/anonymous.png', storage=django.core.files.storage.FileSystemStorage(location='C:\\HACK 2035\\proj\\polls/static/files'), upload_to='', verbose_name='Изображение'),
        ),
    ]
