# Generated by Django 2.1 on 2020-11-16 10:56

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201116_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название документа')),
                ('doc', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\HACK 2035\\proj\\polls/static/files'), upload_to='', verbose_name='Документ-образец')),
                ('mask', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\HACK 2035\\proj\\polls/static/files'), upload_to='', verbose_name='Документ-маска')),
            ],
            options={
                'verbose_name': 'Образец',
                'verbose_name_plural': 'Образцы',
            },
        ),
    ]
