# Generated by Django 2.1 on 2020-11-16 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_docexample'),
    ]

    operations = [
        migrations.AddField(
            model_name='docexample',
            name='conkurs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conkurs', to='polls.Conkurs', verbose_name='Конкурс'),
        ),
    ]
