# Generated by Django 2.1 on 2020-11-16 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_administrator_org_specialist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='user',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
