# Generated by Django 2.1 on 2020-11-16 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20201117_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='user',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Org',
        ),
        migrations.DeleteModel(
            name='Specialist',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
