# Generated by Django 2.1 on 2020-11-16 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_internprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='InternProfile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
