# Generated by Django 2.1 on 2020-11-16 22:31

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20201117_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocZayvka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название документа')),
                ('doc', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\HACK 2035\\proj\\polls/static/files'), upload_to='', verbose_name='Документ')),
                ('mask', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\HACK 2035\\proj\\polls/static/files'), upload_to='', verbose_name='Маска')),
            ],
            options={
                'verbose_name': 'Документ в заявке',
                'verbose_name_plural': 'Документы в заявке',
            },
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Zayvka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conkurs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zay', to='polls.Conkurs', verbose_name='Конкурс')),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org', to='polls.Org', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Завки',
            },
        ),
        migrations.AddField(
            model_name='doczayvka',
            name='zay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zay', to='polls.Zayvka', verbose_name='Заявка'),
        ),
    ]
