# Generated by Django 2.1 on 2020-11-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20201117_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='INN',
            field=models.CharField(default=1, max_length=12, verbose_name='ИНН'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='org',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
    ]
