# Generated by Django 2.1 on 2020-11-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20201117_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docexample',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='doczayvka',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название документа'),
        ),
    ]
