# Generated by Django 2.1 on 2020-11-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20201117_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='conkurs',
            field=models.ManyToManyField(blank=True, to='polls.Conkurs'),
        ),
    ]
